name: flutter_application_1
description: A Virtual Internship & Certificate Generator App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (latest stable versions compatible with Dart 3)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Utility & UI
  file_picker: ^10.2.0
  http: ^1.4.0
  url_launcher: ^6.2.5
  qr_flutter: ^4.1.0
  intl: ^0.20.2

  # QR generation for PDF (manual method)
  qr: ^3.0.2

  # PDF and Printing
  pdf: ^3.10.0
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
