// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjTxzYtE8MqzLt4bN5KS1ArnZnCTCHsA',
    appId: '1:696210364025:web:2a3d68933c3388f8cfa6a8',
    messagingSenderId: '696210364025',
    projectId: 'certificate-5e995',
    authDomain: 'certificate-5e995.firebaseapp.com',
    storageBucket: 'certificate-5e995.firebasestorage.app',
    measurementId: 'G-6G2HYPPLCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbyzDdRXdtKlcixfGUeFCAMy_dQ6KclY0',
    appId: '1:696210364025:android:929d5e00bc67848bcfa6a8',
    messagingSenderId: '696210364025',
    projectId: 'certificate-5e995',
    storageBucket: 'certificate-5e995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJrOXyoEVOWmbq46liOVnCUX-znFg_cNw',
    appId: '1:696210364025:ios:a7ac7c909e654dc9cfa6a8',
    messagingSenderId: '696210364025',
    projectId: 'certificate-5e995',
    storageBucket: 'certificate-5e995.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJrOXyoEVOWmbq46liOVnCUX-znFg_cNw',
    appId: '1:696210364025:ios:a7ac7c909e654dc9cfa6a8',
    messagingSenderId: '696210364025',
    projectId: 'certificate-5e995',
    storageBucket: 'certificate-5e995.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPjTxzYtE8MqzLt4bN5KS1ArnZnCTCHsA',
    appId: '1:696210364025:web:9adc9d307e0b5d8ecfa6a8',
    messagingSenderId: '696210364025',
    projectId: 'certificate-5e995',
    authDomain: 'certificate-5e995.firebaseapp.com',
    storageBucket: 'certificate-5e995.firebasestorage.app',
    measurementId: 'G-NQNBFH8DZV',
  );
}
